#!/bin/sh -e
set -x

autoflake --remove-all-unused-imports --recursive --remove-unused-variables --in-place pythontemplate tests --exclude=__init__.py
black pythontemplate tests
isort pythontemplate tests